# Mana source attribution hotfix.
#
# The 6.13 production parser scans any Oracle line containing "Add". That can
# incorrectly make the source card look like a mana source when the mana text
# actually belongs to a token or another object (Pawn of Ulamog, Treasure
# reminder text, Cryptolith Rite), or when mana is generated by a trigger
# rather than an on-demand activated ability (Lotus Cobra).
#
# For payment planning, only direct activated mana abilities use the source as
# a spendable mana source. Lands retain the produced_mana fallback for unusual
# land wording / implicit mana abilities.

rep("""  const lines = text.split(/\\n+/).map((line) => line.trim()).filter(Boolean);\n  for (const line of lines) {\n    if (!/\\badd\\b/i.test(line)) continue;\n    const colon = line.indexOf(':');\n    const prefix = colon >= 0 ? line.slice(0, colon) : '';\n    const instruction = colon >= 0 ? line.slice(colon + 1) : line;\n    const metadata = activationMetadata(prefix, line);\n""", """  const lines = text.split(/\\n+/).map((line) => line.trim()).filter(Boolean);\n  const directManaLines = lines\n    .map((rawLine) => {\n      let line = String(rawLine || '');\n      // Quoted rules text normally belongs to another object, such as a\n      // created token or a permanent receiving a granted ability.\n      line = line.replace(/[\\\"“][^\\\"”]*[\\\"”]/g, ' ');\n      // Reminder text commonly contains the full rules text for Treasure and\n      // similar tokens. It describes the token, not this source card.\n      let previous = '';\n      while (line !== previous) {\n        previous = line;\n        line = line.replace(/\\([^()]*\\)/g, ' ');\n      }\n      return line.replace(/\\s+/g, ' ').trim();\n    })\n    .filter((line) => {\n      const colon = line.indexOf(':');\n      const addIndex = line.search(/\\badd\\b/i);\n      return colon >= 0 && addIndex > colon;\n    });\n\n  for (const line of directManaLines) {\n    const colon = line.indexOf(':');\n    const prefix = line.slice(0, colon);\n    const instruction = line.slice(colon + 1);\n    const metadata = activationMetadata(prefix, line);\n""", 'direct mana ability ownership')

rep("""  if (!choices.length) {\n    const colors = [...new Set((card.producedMana || card.produced_mana || []).filter((color) => MANA_COLORS.includes(color)))];\n""", """  if (!choices.length && (/\\bLand\\b/i.test(type) || directManaLines.length > 0)) {\n    const colors = [...new Set((card.producedMana || card.produced_mana || []).filter((color) => MANA_COLORS.includes(color)))];\n""", 'restrict produced mana fallback to direct sources')
