# Version marker; multiplayer payload changes because persistent player effects are synchronized.
rep("globalThis.CommanderForgeBuildVersion = '6.13.0';", "globalThis.CommanderForgeBuildVersion = '6.15.0';", 'build version')
rep("const MULTIPLAYER_APP_VERSION = '6.13.0-mp7';", "const MULTIPLAYER_APP_VERSION = '6.15.0-mp8';", 'mp version')

# Persistent per-player effects (needed for effects that last after their source leaves).
rep("""    mulligans: 0,\n    lost: false,\n""", """    mulligans: 0,\n    persistentEffects: [],\n    lost: false,\n""", 'player persistent effects')
rep("""    defaults.commanderCastCount ||= {};\n    defaults.colorIdentity ||= [...new Set(defaults.zones.command.flatMap((card) => card.colorIdentity || []))];\n""", """    defaults.commanderCastCount ||= {};\n    defaults.persistentEffects = Array.isArray(defaults.persistentEffects) ? defaults.persistentEffects : [];\n    defaults.colorIdentity ||= [...new Set(defaults.zones.command.flatMap((card) => card.colorIdentity || []))];\n""", 'normalize persistent effects')

# Persistent no-maximum-hand-size effects.
rep("""  const player = state.players[playerId];\n  if (!player) return { value: 7, label: '7', unlimited: false, manual: false, reasons: [] };\n\n  for (const card of player.zones.battlefield || []) {\n""", """  const player = state.players[playerId];\n  if (!player) return { value: 7, label: '7', unlimited: false, manual: false, reasons: [] };\n\n  for (const effect of player.persistentEffects || []) {\n    if (effect?.type === 'NO_MAX_HAND_SIZE' && effect?.duration === 'game') {\n      unlimited = true;\n      reasons.push(`${effect.sourceName || 'Card effect'}: No maximum hand size for the rest of the game`);\n    }\n  }\n\n  for (const card of player.zones.battlefield || []) {\n""", 'maximum hand persistent')

# Ardyn-style tribal keyword grants: "Demons you control have ...".
rep("""    /other ([A-Za-z -]+) creatures you control have ([^.]+)/gi,\n    /(?:equipped|enchanted) creature has ([^.]+)/gi,\n""", """    /other ([A-Za-z -]+) creatures you control have ([^.]+)/gi,\n    /(?:^|\\n)(?:other )?([A-Za-z][A-Za-z '-]+?)s you control have ([^.]+)/gi,\n    /(?:equipped|enchanted) creature has ([^.]+)/gi,\n""", 'granted keyword parser')
rep("""    const tribal = text.match(/other ([A-Za-z -]+) creatures you control have/i);\n    if (tribal && subtypeMatches(target, tribal[1])) rules.grantedKeywords.forEach((keyword) => grants.add(keyword));\n""", """    const tribal = text.match(/other ([A-Za-z -]+) creatures you control have/i);\n    if (tribal && subtypeMatches(target, tribal[1])) rules.grantedKeywords.forEach((keyword) => grants.add(keyword));\n    const directTribal = text.match(/(?:^|\\n)(?:other )?([A-Za-z][A-Za-z '-]+?)s you control have/i);\n    if (directTribal) {\n      const subtype = String(directTribal[1] || '').trim().replace(/s$/i, '');\n      if (subtype && subtypeMatches(target, subtype)) rules.grantedKeywords.forEach((keyword) => grants.add(keyword));\n    }\n""", 'derived direct tribal')

# Helpers for Ardyn copy tokens, d20 effects, and generic ability coverage.
needle="""function smartPendingEffectState(effect, state) {\n  const text = effectResolutionText(effect?.text || '');\n"""
insert="""function copyTokenTypeLine(sourceCard, subtype = 'Demon') {\n  const type = String(sourceCard?.typeLine || 'Creature').trim();\n  const supertypeWords = ['Basic', 'Legendary', 'Snow', 'World', 'Ongoing'];\n  const prefix = supertypeWords.filter((word) => new RegExp(`\\\\b${word}\\\\b`, 'i').test(type)).join(' ');\n  return `${prefix ? `${prefix} ` : ''}Creature — ${subtype}`;\n}\n\nfunction makeEffectCopyToken(sourceCard, controllerId, draft, overrides = {}) {\n  const copy = deepClone(sourceCard);\n  copy.instanceId = uid('copy');\n  copy.token = true;\n  copy.predefinedToken = false;\n  copy.stackFresh = true;\n  copy.commander = false;\n  copy.controller = controllerId;\n  copy.owner = controllerId;\n  copy.tapped = Boolean(overrides.tapped || false);\n  copy.attacking = false;\n  copy.attackTargetPlayerId = null;\n  copy.blocking = null;\n  copy.blockedBy = [];\n  copy.attachedTo = null;\n  copy.attachments = [];\n  copy.counters = {};\n  copy.damageMarked = 0;\n  copy.deathtouchDamaged = false;\n  copy.abilityActivationsThisTurn = {};\n  copy.enteredBattlefieldTurn = Number(draft.turnNumber || 1);\n  copy.summoningSick = true;\n  if (overrides.colors) copy.colors = [...overrides.colors];\n  if (overrides.typeLine) copy.typeLine = overrides.typeLine;\n  if (overrides.power !== undefined) copy.power = String(overrides.power);\n  if (overrides.toughness !== undefined) copy.toughness = String(overrides.toughness);\n  copy.copySourceOracleId = sourceCard.oracleId || null;\n  copy.copySourceName = sourceCard.name || '';\n  copy.copyEffectOverrides = deepClone(overrides);\n  return copy;\n}\n\nfunction secureDieRoll(sides = 20) {\n  const faces = Math.max(2, Math.floor(Number(sides || 20)));\n  try {\n    if (globalThis.crypto?.getRandomValues) {\n      const limit = Math.floor(0x100000000 / faces) * faces;\n      const values = new Uint32Array(1);\n      do globalThis.crypto.getRandomValues(values); while (values[0] >= limit);\n      return (values[0] % faces) + 1;\n    }\n  } catch {}\n  return Math.floor(Math.random() * faces) + 1;\n}\n\nfunction abilityCoverageForCard(card) {\n  const compiler = globalThis.CommanderForgeOracleCompilerV8 || globalThis.CommanderForgeOracleCompilerV7;\n  if (compiler?.compileCardAbilities) {\n    try { return compiler.compileCardAbilities(card, { cardName: card?.name || '' }); } catch (error) { console.warn('[Commander Forge Ability Coverage]', error); }\n  }\n  const abilities = oracleAbilityLines(card).map((text) => ({ text, abilityType: /^(?:when|whenever|at)\\b/i.test(text) ? 'triggered' : text.includes(':') ? 'activated' : 'manual', automation: 'manual', reason: 'No structured adapter is available yet.' }));\n  return { abilities, automated: 0, assisted: 0, manual: abilities.length, coverage: abilities.length ? 0 : 1 };\n}\n\nfunction smartPendingEffectState(effect, state) {\n  const text = effectResolutionText(effect?.text || '');\n"""
rep(needle,insert,'insert ability helpers')

# Smart resolver descriptors: Ardyn and Ancient Silver Dragon.
rep("""  const fight = fightEffectDescriptor(text);\n""", """  const d20DrawNoMax = text.match(/roll a d20\\.\\s*draw cards equal to the result\\.\\s*you have no maximum hand size for the rest of the game/i);\n  if (d20DrawNoMax) {\n    return { kind: 'roll-die-draw-no-max', cards: [], playerId: effect.controllerId, sides: 20 };\n  }\n\n  const graveyardCopy = text.match(/exile up to one target creature card from a graveyard\\.\\s*if you exiled a card this way, create a token (?:that|that's|that’s) a copy of that card, except (?:it|it's|it’s) a (\\d+)\\/(\\d+) ([a-z]+) ([a-z][a-z -]*)/i);\n  if (graveyardCopy) {\n    const cards = Object.values(state.players || {}).flatMap((player) => player.zones?.graveyard || []).filter(isCreature);\n    return {\n      kind: 'exile-graveyard-copy-token',\n      cards,\n      playerId: effect.controllerId,\n      zeroAllowed: true,\n      power: Number(graveyardCopy[1]),\n      toughness: Number(graveyardCopy[2]),\n      colorWord: String(graveyardCopy[3]).toLocaleLowerCase(),\n      subtype: String(graveyardCopy[4]).trim().replace(/[.]+$/, ''),\n      noResultReason: cards.length ? null : 'no-creature-card-in-graveyard',\n    };\n  }\n\n  const fight = fightEffectDescriptor(text);\n""", 'smart special descriptors')

# No-result labels for optional Ardyn target.
rep("""    'graveyard-move': 'Graveyard effect resolved without choosing a card.',\n  };\n""", """    'graveyard-move': 'Graveyard effect resolved without choosing a card.',\n    'exile-graveyard-copy-token': 'Resolved with no creature card exiled.',\n  };\n""", 'no result label')

# Ardyn resolution before generic create-token.
rep("""  const smart = smartPendingEffectState(effect, current);\n  if (smart.kind === 'create-token') {\n""", """  const smart = smartPendingEffectState(effect, current);\n  if (smart.kind === 'exile-graveyard-copy-token') {\n    if (!cardId) return resolveSmartPendingEffectNoResult(effectId);\n    const target = smart.cards.find((card) => card.instanceId === cardId);\n    if (!target) return { ok: false, message: 'Choose a creature card from a graveyard.' };\n    updateState((draft) => {\n      const located = findCard(cardId, draft);\n      if (!located || located.zone !== 'graveyard' || !isCreature(located.card)) return;\n      const exiled = located.container.splice(located.index, 1)[0];\n      exiled.controller = exiled.owner;\n      exiled.tapped = false;\n      exiled.attacking = false;\n      exiled.attackTargetPlayerId = null;\n      exiled.blocking = null;\n      exiled.blockedBy = [];\n      draft.players[exiled.owner].zones.exile.push(exiled);\n      recordZoneTransition(draft, { card: exiled, actorId: effect.controllerId, subjectPlayerId: exiled.owner, fromZone: 'graveyard', toZone: 'exile', castAttempt: false });\n\n      const colorMap = { white: 'W', blue: 'U', black: 'B', red: 'R', green: 'G', colorless: 'C' };\n      const token = makeEffectCopyToken(exiled, effect.controllerId, draft, {\n        colors: [colorMap[smart.colorWord] || 'B'],\n        typeLine: copyTokenTypeLine(exiled, smart.subtype || 'Demon'),\n        power: smart.power,\n        toughness: smart.toughness,\n        copyEffect: effect.sourceName,\n      });\n      draft.players[effect.controllerId].zones.battlefield.push(token);\n      enqueueBattlefieldEntryEffects(draft, token, 'copy-token-effect');\n      draft.pendingTriggers = draft.pendingTriggers.filter((item) => item.id !== effectId);\n      draft.selected = { instanceId: token.instanceId };\n    }, { log: `${effect.sourceName}: exiled ${target.name} and created a ${smart.power}/${smart.toughness} ${smart.colorWord} ${smart.subtype} token copy of it.` });\n    return { ok: true, message: `${target.name} was exiled and copied as a ${smart.power}/${smart.toughness} ${smart.subtype}. Its copied enter-the-battlefield abilities were queued normally.` };\n  }\n  if (smart.kind === 'create-token') {\n""", 'ardyn resolver')

# D20 resolver as a dedicated action, placed before multi resolver.
needle="""function resolveSmartPendingEffectMulti(effectId, cardIds = [], powerOverrides = {}) {\n"""
insert="""function resolveSmartRandomEffect(effectId) {\n  const current = window.CommanderForge.getState();\n  const effect = current.pendingTriggers.find((item) => item.id === effectId);\n  if (!effect) return { ok: false, message: 'Pending effect not found.' };\n  const smart = smartPendingEffectState(effect, current);\n  if (smart.kind !== 'roll-die-draw-no-max') return { ok: false, message: 'This effect does not have an automated die roll.' };\n  const result = secureDieRoll(smart.sides || 20);\n  updateState((draft) => {\n    const player = draft.players[smart.playerId];\n    for (let i = 0; i < result; i += 1) {\n      drawCards(draft, smart.playerId, 1);\n      emitGameEvent(draft, { type: 'draw', actorId: smart.playerId, amount: 1 });\n    }\n    player.persistentEffects ||= [];\n    if (!player.persistentEffects.some((item) => item?.type === 'NO_MAX_HAND_SIZE' && item?.duration === 'game')) {\n      player.persistentEffects.push({\n        id: uid('persistent'),\n        type: 'NO_MAX_HAND_SIZE',\n        duration: 'game',\n        sourceCardId: effect.sourceCardId || null,\n        sourceName: effect.sourceName,\n        createdTurn: draft.turnNumber,\n      });\n    }\n    draft.pendingTriggers = draft.pendingTriggers.filter((item) => item.id !== effectId);\n    checkLosses(draft);\n  }, { log: `${effect.sourceName}: rolled a d${smart.sides || 20} → ${result}; drew ${result} card${result === 1 ? '' : 's'} and gained no maximum hand size for the rest of the game.` });\n  return { ok: true, result, message: `D${smart.sides || 20}: ${result}. Drew ${result} card${result === 1 ? '' : 's'}. You have no maximum hand size for the rest of the game.` };\n}\n\nfunction resolveSmartPendingEffectMulti(effectId, cardIds = [], powerOverrides = {}) {\n"""
rep(needle,insert,'random resolver')
