# Combat-damage event matching.
rep("""  if (event.type === 'ability-activated') {\n""", """  if (event.type === 'combat-damage-player') {\n    if (!/\\bdeals? combat damage to (?:a player|an opponent|one or more players)\\b/.test(text)) return false;\n    const selfNamed = text.includes(String(sourceCard?.name || '').toLocaleLowerCase());\n    if (/\\b(?:this creature|this permanent) deals? combat damage\\b/.test(text) || selfNamed) {\n      return sourceCard.instanceId === event.card?.instanceId;\n    }\n    if (!cardMatchesEventSubject(event.card, condition)) return false;\n    return triggerSubjectControlMatches(condition, sourceCard, event.card);\n  }\n\n  if (event.type === 'ability-activated') {\n""", 'combat event match')
rep("""  if (['cast', 'sacrifice'].includes(event.type) && event.card && !sources.some((card) => card.instanceId === event.card.instanceId)) sources.push(event.card);\n""", """  if (['cast', 'sacrifice', 'combat-damage-player'].includes(event.type) && event.card && !sources.some((card) => card.instanceId === event.card.instanceId)) sources.push(event.card);\n""", 'event source LKI')

# Public/assisted reporting of combat damage for manual/online games.
needle="""function addCounter(instanceId, counter, delta) {\n"""
insert="""function reportCombatDamage(instanceId, targetPlayerId, amount = 1) {\n  const current = window.CommanderForge.getState();\n  const found = findCard(instanceId, current);\n  if (!found || found.zone !== 'battlefield') return { ok: false, message: 'Choose a battlefield creature that dealt combat damage.' };\n  if (!current.players[targetPlayerId] || targetPlayerId === (found.card.controller || found.playerId)) return { ok: false, message: 'Choose an opponent that was dealt combat damage.' };\n  const damage = Math.max(1, Number(amount || 1));\n  updateState((draft) => {\n    const located = findCard(instanceId, draft);\n    const sourceCard = located?.card || deepClone(found.card);\n    emitGameEvent(draft, { type: 'combat-damage-player', actorId: sourceCard.controller || sourceCard.owner, targetPlayerId, amount: damage, card: sourceCard });\n  }, { log: `${found.card.name}: recorded combat damage to ${current.players[targetPlayerId].name}; matching combat-damage triggers were queued.` });\n  return { ok: true, message: `${found.card.name}'s combat-damage trigger(s) were checked.` };\n}\n\nfunction addCounter(instanceId, counter, delta) {\n"""
rep(needle,insert,'manual combat damage reporter')

# Automated bot combat records exact source snapshots, then game layer consumes them.
rep("""function resolveMarkedCombat(original, attackerPlayerId) {\n  const state = deepClone(original);\n  state._coach ||= { virtual: {}, actionNotes: [], newPermanents: [], castCards: [], combatDamage: 0, effectsBySource: {} };\n""", """function resolveMarkedCombat(original, attackerPlayerId) {\n  const state = deepClone(original);\n  state._forgeResolvedCombatEvents = [];\n  state._coach ||= { virtual: {}, actionNotes: [], newPermanents: [], castCards: [], combatDamage: 0, effectsBySource: {} };\n""", 'bot event init')
rep("""    if (attacker.commander && Number(outcome.rawDamage || 0) > 0) {\n      const sourceId = (attacker.mutationPile || []).find((part) => part.commander)?.instanceId || attacker.instanceId;\n      opponent.commanderDamage[sourceId] = Number(opponent.commanderDamage[sourceId] || 0) + Number(outcome.rawDamage || 0);\n    }\n""", """    if (attacker.commander && Number(outcome.rawDamage || 0) > 0) {\n      const sourceId = (attacker.mutationPile || []).find((part) => part.commander)?.instanceId || attacker.instanceId;\n      opponent.commanderDamage[sourceId] = Number(opponent.commanderDamage[sourceId] || 0) + Number(outcome.rawDamage || 0);\n    }\n    if (Number(outcome.rawDamage || 0) > 0) {\n      state._forgeResolvedCombatEvents.push({\n        type: 'combat-damage-player',\n        actorId: attackerPlayerId,\n        targetPlayerId: opponentId,\n        amount: Number(outcome.rawDamage || 0),\n        card: deepClone(attacker),\n      });\n    }\n""", 'bot event record')

# Game-layer processor is added near reportCombatDamage.
rep("""function reportCombatDamage(instanceId, targetPlayerId, amount = 1) {\n""", """function processResolvedCombatEvents() {\n  const current = window.CommanderForge.getState();\n  const events = Array.isArray(current._forgeResolvedCombatEvents) ? current._forgeResolvedCombatEvents : [];\n  if (!events.length) return { ok: true, count: 0 };\n  updateState((draft) => {\n    const pending = [...(draft._forgeResolvedCombatEvents || [])];\n    draft._forgeResolvedCombatEvents = [];\n    for (const event of pending) emitGameEvent(draft, event);\n  }, { snapshot: false, log: events.length ? `Commander Forge checked ${events.length} combat-damage event${events.length === 1 ? '' : 's'} for triggers.` : null });\n  return { ok: true, count: events.length };\n}\n\nfunction reportCombatDamage(instanceId, targetPlayerId, amount = 1) {\n""", 'process auto combat events')

# Bot invokes combat trigger processing after state commit.
rep("""  botCommitState(result, 'resolved combat damage');\n  bot.pendingCombat = null;\n""", """  botCommitState(result, 'resolved combat damage');\n  processResolvedCombatEvents();\n  bot.pendingCombat = null;\n""", 'bot process combat triggers')

# Smart pending UI for the two end-to-end examples.
rep("""  if (smart.kind === 'search-library') {\n""", """  if (smart.kind === 'roll-die-draw-no-max') {\n    return `<div class=\"mana-choice-group\"><div class=\"small muted wide\"><strong>D${smart.sides || 20} roll recognized.</strong> Forge will roll, draw cards equal to the result, and remember the no-maximum-hand-size effect for the rest of the game.</div><button class=\"btn small-btn primary\" data-action=\"smart-effect-roll\" data-effect-id=\"${effect.id}\">🎲 Roll D${smart.sides || 20} & resolve</button><button class=\"btn small-btn ghost\" data-action=\"resolve-effect\" data-effect-id=\"${effect.id}\">Resolve manually</button></div>`;\n  }\n\n  if (smart.kind === 'exile-graveyard-copy-token') {\n    if (!smart.cards.length) return `<div class=\"mana-choice-group\"><span class=\"small muted wide\">No creature card is currently in a graveyard. Choosing no target is legal.</span><button class=\"btn small-btn ghost\" data-action=\"smart-effect-no-result\" data-effect-id=\"${effect.id}\">Resolve with no target</button></div>`;\n    return `<div class=\"mana-choice-group\"><div class=\"small muted wide\"><strong>Graveyard copy recognized.</strong> Choose up to one creature card from any graveyard. Forge will exile it, create the modified copy token, preserve the copied abilities, and queue copied ETB triggers.</div>${smart.cards.slice(0, 40).map((card) => `<button class=\"btn small-btn primary\" data-action=\"smart-effect-card\" data-effect-id=\"${effect.id}\" data-card-id=\"${card.instanceId}\">Exile & copy ${escapeHtml(card.name)}</button>`).join('')}<button class=\"btn small-btn ghost\" data-action=\"smart-effect-no-result\" data-effect-id=\"${effect.id}\">Choose no target</button><button class=\"btn small-btn ghost\" data-action=\"resolve-effect\" data-effect-id=\"${effect.id}\">Resolve manually</button></div>`;\n  }\n\n  if (smart.kind === 'search-library') {\n""", 'smart ui specials')

# Pending card-use helper accepts Ardyn's any-graveyard choice.
rep("""      && smart.kind === 'graveyard-move'\n""", """      && ['graveyard-move', 'exile-graveyard-copy-token'].includes(smart.kind)\n""", 'pending graveyard use')

# Multiplayer permission knows new resolving action.
rep("""'open-library-effect-picker', 'choose-effect-opponent'].includes(action)""", """'open-library-effect-picker', 'choose-effect-opponent', 'smart-effect-roll'].includes(action)""", 'multiplayer action set')

# Button handler for roll and assisted combat-damage report.
rep("""    if (action === 'smart-effect-card') handleResult(resolveSmartPendingEffect(button.dataset.effectId, button.dataset.cardId));\n""", """    if (action === 'smart-effect-card') handleResult(resolveSmartPendingEffect(button.dataset.effectId, button.dataset.cardId));\n    if (action === 'smart-effect-roll') {\n      const result = resolveSmartRandomEffect(button.dataset.effectId);\n      handleResult(result);\n      if (result?.ok) toast(result.message);\n    }\n""", 'roll action handler')
rep("""    if (action === 'toggle-attack') { const result=toggleAttack(button.dataset.cardId); if (result?.needsAttackTarget) { ui.attackTargetPicker={cardId:button.dataset.cardId}; render({force:true}); } else handleResult(result); }\n""", """    if (action === 'toggle-attack') { const result=toggleAttack(button.dataset.cardId); if (result?.needsAttackTarget) { ui.attackTargetPicker={cardId:button.dataset.cardId}; render({force:true}); } else handleResult(result); }\n    if (action === 'report-combat-damage') handleResult(reportCombatDamage(button.dataset.cardId, button.dataset.targetPlayerId, Number(button.dataset.amount || 1)));\n""", 'combat report action')
